version: '3'

services:
    node-app:
        build: .
        ports:
            - '8080:8080'
            - '9229:9229'
        volumes:
            - .:/app
        command: npm run dev
        restart: unless-stopped
        networks:
            - app-net
        container_name: node-server
        env_file:
            - .env
    dynamodb:
        image: amazon/dynamodb-local
        ports:
            - '8000:8000'
        container_name: dynamodb-local
        hostname: dynamodb-local
        networks:
            - app-net
        command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]

networks:
    app-net:

volumes:
    db_data:
