version: '3.2'

services:
    node-test-app:
        build: .
        ports:
            - '8080:8080'
        volumes:
            - .:/app
        command: npm run test
        networks:
            - app-test-net
        container_name: node-test-server
        environment:
            - GOOGLE_APIS_SERVICE_ACCOUNT_CREDENTIALS_BASE_64=ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiZmlubmlzaC10cmFuc2xhdG9yLWFwaSIsCiAgInByaXZhdGVfa2V5X2lkIjogIjU5NDQ1NGYyNTkyMDc0MDBmOTQ3MDg2MjU2MTkyYWMyNjNjNjk3NWEiLAogICJwcml2YXRlX2tleSI6ICItLS0tLUJFR0lOIFBSSVZBVEUgS0VZLS0tLS1cbk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ2dqNng0MDZOL3d6NS9cbmhlSzJFdW56Z3hGNUJUUmVjSVFkK2ptU3FoMGNvOUYzMDJBM1llMzk3eDhySGZDN1N6T0VKTUlNTC9oMzBzMm9cbjJNWjBERlg5L0VaUnJjaFYvTVpIektWZnpVL3NoV1ZacU9wdldoZU1INmJEY3VCNEV3dTlkY1Z5bURCVTF3MTFcbmE0N0VzSjd2eVBoK3NkVWVObTE0L2ZmTVNDRjc2amY0T1c3NThmdURzZVd6TVg4WUVDc1RBU01nMWt4cEZOUXdcblNvZE9MUWNpU21ZN09JLzVsaXJOcnVvS3l5YWlRT0pxQ3BmK0FMcll5aXg2a0ovd2lTcDNBWEZRMXA2emd1eTlcbml1QkY5MFZNNEVXczhYVXAraExXN0VpVGdRaVo2bURuMG5icUovYnhxdE9tRHVWYlI4L0xtclMxUU5hTmVWVWZcbjFOZ25yNE1UQWdNQkFBRUNnZ0VBU3VsZHJlNElmWWFwdFRQUlIrUGhOWlUwWk1OeDRKSWNnaVFLRW95K0VtdTRcblFuRGpsbE5oaDdXMlZCYWZCN09aY0pENTNGZlJWSTZORjdjME9GYTlGRWhNd3JVVElGTlVhNUZtb3lFV3BpTENcbjI2Yzg0Z0VsdFdIYkc1dVFjVlZwaDliWDdaUm1FRjlaenl3RXEyNUFhVjNaMnJxNzFXSE5oOEx1aDJnci96VFdcbkFVVHIvUGFmc3hnU1dZeVB4KzR4Y2kvb1BlMXZQSlZaM0wzaysrajliV0RUVU1jVWNpMHBPWDdranZhajM2WHFcbmdqcEZvYmNPUFVLUVFtYkErcVVCRHVyMC91NDNtcUsxVEJwL25jY3JYRGw5K2F2V3I2UUJMT1F2NWQzSHZJRkdcbjNPOHd2RmxKaEprMldQd3h2bkV3aHF1OHBtTkRHWmF4aUg3cEZoQUdhUUtCZ1FETWZUOSt6RGFsMFhZWFZOZ2RcbnZ0dm43WVhRRVljckhwL00wdmhIVjZaajRRMm5mQ1NyYVgxb0JXbldTU2U1UEVldTNUb2NXVEo5UFBUZWdSbVFcbmg1S1NrMDVUejZsQWowVG1wYXBuS05YYVgxeFIzbDZhajhmOHM3Ym44OERZaTVycWpPZ2VPL0Q0c0dSc0FZamhcbkZ0TnhVSC9pZzFoZ2hYYnhsQWdFc3RZNFh3S0JnUURKQWF1cjlra0ZxTXFrYjFJUFkwamRCclhtNGZOZVFnRXJcblIreDRVN1c4eTdBZ1hNaVZBZEFMUmNsVmc0Ris2U2t1aG9VdkF4MG9qTHN5QlFieGhxS0ZaM0FTRDROVWdadU5cbktDbW1QeCszaWhxYUdzdnpOb0Exd3JieThrVllIWEJsV1daSzlDeHgrRFpRVU5aMzZzZUR3NUNidll6c0xKVFBcbm82eVltNVFCelFLQmdGMlkwbkJLTHBVMVM1VWdTNDlKNWNQQmp5Y09iczBJeG1IdENxRTArRDd0S3QvSFRjMTdcbmltQUxZa2NuMHR2UlFJcEVUaTNka2VPSy9CWEFCNkNFdlUwRHlhMUk5cEpMUVdGRTRMczVFTEZVUnFCZVpQVGZcbjdNeTR3WFpudHBRblNqQWpjTGN0L24wRjErRXJ6cWdnVjRXZEwvdlEzS25KVFFrRUZhdDQ0OTZIQW9HQkFLWHdcbkNpQUpUdGtzTWpZemJFUWx5NllqL3hFZW9VSEVMYURrWEhRdGJ3L3YrM09NQlU3MTB5RXJPSDJ1OWIybWtJZkhcbko3WGExVHgvaVo1T2hoL243TTFDeWtNdXFWV2ZOYUgvY1BxOGk5dUNXRm0yRzM2cUZJZk5PaWt3RmswYTZJblNcbmx0N3oycWt2cHU4QS9UeThCbjloZUVVSjQ0ZXBlaVE4VTZVY2NzQlZBb0dCQU1MWkd1ZFRvSytDQnAzUkpsVy9cblBBWXlla0pyV2hLOHZLTzhtN05Mb09YRUhtb2ZHWEpqOFMzT2lYL0d2bVFzSUI1RFh5aEU1YmtzWTFKdDM5Ui9cbnB4RU9nRGhpV0tTNXExYkxrVEw2Q1Vmd0d4UVFIenZ3Rmw2TytzY3ptUWpSaDRyeTRLcUZtTDdkSkljZGZLWWNcblNCVWprMEg5NmZxQTQzWHRjT1g2MFBaTFxuLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLVxuIiwKICAiY2xpZW50X2VtYWlsIjogImZpbm5pc2gtdHJhbnNsYXRvci1hcGktc2FAZmlubmlzaC10cmFuc2xhdG9yLWFwaS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNsaWVudF9pZCI6ICIxMDgyNDg1MTkyNzY5NjgyMjgzOTIiLAogICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2Zpbm5pc2gtdHJhbnNsYXRvci1hcGktc2ElNDBmaW5uaXNoLXRyYW5zbGF0b3ItYXBpLmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9
            - SERVER_PORT=8080
            - AWS_REGION=eu-central-1
            - AWS_ENDPOINT=http://dynamodb-test:8000
            - AWS_NODEJS_CONNECTION_REUSE_ENABLED=1
            - AWS_ACCESS_KEY_ID=AKIAUFXQ5PYAK3YYWNEX
            - AWS_SECRET_ACCESS_KEY=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
            - NODE_ENV=test
    dynamodb:
        image: amazon/dynamodb-local
        ports:
            - '8000:8000'
        container_name: dynamodb-test
        hostname: dynamodb-test
        networks:
            - app-test-net
        command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]

networks:
    app-test-net:
