version: '3'

services:
    node-app:
        build: .
        ports:
            - '8000:8000'
            - '9229:9229'
        volumes:
            - .:/app
        command: npm run dev
        restart: unless-stopped
        networks:
            - redis-net
    redis-server:
        image: 'redis:5.0-alpine'
        command: redis-server --appendonly yes
        volumes:
            - redis-data:/data
        networks:
            - redis-net

networks:
    redis-net:

volumes:
    redis-data:
