version: '3'

services:
    node-app:
        build: .
        ports:
            - '8000:8000'
            - '9229:9229'
        volumes:
            - .:/app
        command: npm run dev
        restart: unless-stopped
    redis-server:
        image: 'redis'
