version: '3.2'

services:
    node-test-app:
        build: .
        ports:
            - '8080:8080'
        volumes:
            - .:/app
        command: npm run test
        networks:
            - app-test-net
        container_name: node-test-server
        env_file:
            - .env-test
    dynamodb:
        image: amazon/dynamodb-local
        ports:
            - '8000:8000'
        container_name: dynamodb-test
        hostname: dynamodb-test
        networks:
            - app-test-net
        command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]

networks:
    app-test-net:
